resolver: lts-9.21
compiler: ghcjs-0.2.1.9009021_ghc-8.0.2
compiler-check: match-exact
setup-info:
  ghcjs:
    source:
      ghcjs-0.2.1.9009021_ghc-8.0.2:
        url: https://github.com/matchwood/ghcjs-stack-dist/raw/master/ghcjs-0.2.1.9009021.tar.gz
        sha1: b1740c3c99e5039ac306702894cd6e58283f4d31

packages:
- '.'
- ../common

flags:
  miso:
    jsaddle: true


allow-newer: true
extra-deps:
  - jsaddle-warp-0.9.5.0
  - miso-0.21.1.0
  - servant-0.12.1
  - cabal-doctest-1.0.6
